### ISSUE TITLE
Passing in containerRequired = false

### ISSUE THREAD

**Issue by jdarling** [nylas/component-store-example#4]
How exactly do you pass in the containerRequired as false?  I've tried several different approaches but can't seem to figure it out.  Any pointers would be great.

**Comment by grinich** [comment]
@bengotow :smile:

**Comment by bengotow** [comment]
Hey @jdarling — it looks like the sample code was actually broken, and passing `containerRequired: false` caused the component not to render. I've pushed a fix for that problem. Here's how you can add the containerRequired: false flag to your components:

```
// Old-style constructor syntax
MarkAsReadComponent = React.createClass
  displayName: 'MarkAsReadComponent'
  statics:
    containerRequired: false

// Coffeescript class syntax
class MarkAsReadComponent extends React.Component
  @displayName: 'MarkAsReadComponent'
  @containerRequired: false
```

Hope that helps!

**Comment by jdarling** [comment]
That makes sense.  I found the change ("component" to component) in the generated JavaScript (I don't use CoffeeScript) and a few other opportunities for improvement that once I'm done with my current project I'll try to backport and PR for.  Have to say this is a really nice starting point.

Few notes on trip-up's I've ran into:
- It wasn't obvious that you have to implement the filter methods for InjectedComponentSet to actually work when using matching
- It's {{role: 'component-type'}} not {role: 'component-type}
- Added tagName to ICS as if your using bootstrap and want to do things like wrap nav items you don't want div's you want ul's and li's.
- MessageStore is specific to your example (yeah, bit of egg on my face when I realized I didn't actually need it)
- Still don't know what injected-component-label is actually for?
- Injected-component would be better if it could be used for page routing, EG: displayed current "component" property from list of available.  Just an idea.

Still, great work and so glad I ran across your blog post on the subject.  Got me started toward a modular frontend to fit my logging, monitoring, analytics dashboard thing :D
